config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users

  resources :expenses do
    collection do
      get 'category/:category', to: 'expenses#category', as: 'category'
      get 'reports/index'
    end
  end
  
  root 'expenses#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"] 
         end 
          
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :expenses, dependent: :destroy

    def self.ransackable_associations(auth_object = nil)
        ["expenses"]
      end
      def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "id_value", "name", "updated_at"]
      end  
end

app/models/expense.rb
class Expense < ApplicationRecord
  searchkick  
  belongs_to :category
  belongs_to :user
  has_one_attached :receipt

  validates :title, presence: true, length: { maximum: 100 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :date, presence: true
  validates :category, presence: true

  validate :receipt_size_validation
  validate :date_cannot_be_in_the_future

  def self.ransackable_associations(auth_object = nil)
    ["category", "receipt_attachment", "receipt_blob", "user"]
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["amount", "category_id", "created_at", "date", "description", "id", "id_value", "title", "updated_at", "user_id"]
  end

  def self.monthly_spending
    group_by_month(:date, last: 12, current: true).sum('expenses.amount')
  end

  def self.search(search)
    if search
      category = Category.find_by(name: search)
      if category
        self.where(category_id:category)
      else
        Expense.all
      end 
    else 
       Expense.all
    end  
  end 

  private

  def receipt_size_validation
    if receipt.attached? && receipt.blob.byte_size > 10.megabytes
      errors.add(:receipt, 'size should be less than 10MB')
    end
  end
  
  def date_cannot_be_in_the_future
    if date.present? && date > Date.today
      errors.add(:date, "can't be in the future")
    end
   end 

end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_welcome_email
  
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }
  
  
  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = current_user.expenses.search(params[:search]).page(params[:page]).per(6)
  end

  def category
    puts "------#{params[:category]}"

    @expenses = current_user.expenses.where(category_id: params[:category]).page(params[:page]).per(6)
    
     respond_to do |format|
      format.html { render :index }
      format.html   { render partial: 'expenses' }
     end
    
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = current_user.expenses.build(expense_params)
    if @expense.save
      redirect_to @expense, notice: 'Expense was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy!

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
   def expense_params
      params.require(:expense).permit(:title, :amount, :description, :date, :category_id, :receipt, :search)
   end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @expenses_by_category = current_user.expenses.group(:category).sum(:amount)
    @expenses_by_month = current_user.expenses.group_by_month(:date).sum(:amount)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>
<div class="pagination">
  <%= paginate @expenses %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/expenses/_expense.html.erb
<div class="col-md-4 mb-4">
<div class="card h-100" style="width: 15rem;">
<% if expense.receipt.attached? %>
<%= image_tag expense.receipt, size: "200x200",class:"card-img-top",style:"height:200px" %>
  <% else %>
    No receipt uploaded.
  <% end %>
</p>
  <div class="card-body">
    <h5 class="card-title"><%= expense.title %>&nbsp; </h5>
    <h6 class="card-subtitle mb-2 text-muted">$<%= expense.amount %></h6>
    <p class="card-text"><%= expense.description %></p>
    
    <%= link_to "Show this expense", expense ,class:"btn btn-primary" %>
    
  </div>
  <div class="card-footer">
      <small class="text-muted"><%= expense.date %></small>
  </div>
</div>
</div>

app/views/expenses/_expenses.html.erb
<div id="expenses" class="row">

  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
 
</div>

app/views/expenses/_form.html.erb
<div class="container">
<div class="row">
<div class="col-12 d-flex justify-content-center">
<div class="card w-25">
<div class="card-body">
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    
    <%= form.text_field :title ,{ class:"form-control",placeholder:"Title"} %>
  </div>

  <div class="mb-3">
    
    <%= form.text_field :amount ,{ class:"form-control",placeholder:"Amount"} %>
  </div>

  <div class="mb-3">
    
    <%= form.text_area :description,{ class:"form-control",placeholder:"Description"} %>
  </div>

  <div class="mb-3">
    
    <%= form.date_field :date , { class:"form-control",placeholder:"Date" } %>
  </div>

  <div class="field mb-3">
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true %>
</div>

   <div class="field mb-3">
   <%= form.label :receipt ,{class:"form-label "} %>
   <%= form.file_field :receipt ,{ class:"form-control",placeholder:"Receipt"} %>
   </div>
  
  <div class="mb-3">
    <%= form.submit "Submit",class:"btn btn-primary" %>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/expenses/edit.html.erb
<center><h1>Editing expense</h1></center>

<%= render "form", expense: @expense %>
<br>

<div class="d-flex justify-content-center">
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<div class="container">

<%= link_to "New expense", new_expense_path ,class:"btn btn-secondary mb-5" %>

<div class="btn-group mb-5" role="group" aria-label="Basic mixed styles example">
  <%= link_to "All", expenses_path, class: "btn btn-danger", remote: true %>
  <%= link_to "Repairs", category_expenses_path(2), class: "btn btn-warning", remote: true %>
  <%= link_to "Shopping", category_expenses_path(1), class: "btn btn-success", remote: true %>
  <%= link_to "Bills", category_expenses_path(3), class: "btn btn-info", remote: true %>
  <%= link_to "Taxes", category_expenses_path(4), class: "btn btn-primary", remote: true %>
</div>

 <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
 <% sum = 0%>
 <% @expenses.each do |e| %>
 <% sum+=e.amount %>
 <% end %>

 <h3>Total: $<%=sum%></h3>
</div>



<div id="expenses" class="row">
  <% if !@expenses.blank?%>
  <%= render @expenses %>
  <% else %>
  <h1>NO EXPENCES AVAILABLE</h1>
  <% end%>
</div>

<div class="pagination">
  <ul class="pagination">
  <li class:"page-item"><%= paginate @expenses%></li>
  </ul>
</div>


</div>

app/views/expenses/new.html.erb
<center><h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", expenses_path %>
</div>
</center>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<center>
<div class="card mb-3 mt-3" style="max-width: 600px;">
<div class="row g-0">
  <div class="col-md-4">
  <% if @expense.receipt.attached? %>
  <%= image_tag @expense.receipt, size: "200x200" %>
<% else %>
  No receipt uploaded.
<% end %>
  </div>
  <div class="col-md-8">
    <div class="card-body">
      <h4 class="card-title"><%=@expense.title%></h4>
      <p class="card-text"> Description : <%=@expense.description%></p>
      <p class="card-text"> $<%=@expense.amount%></p>
      <p class="card-text"><small class="text-muted"><%=@expense.date%></small></p>
    </div>
  </div>
</div>
</div>
  
  

<div class="mb-3">
  <%= link_to "Edit this expense", edit_expense_path(@expense) ,class:"btn btn-primary mb-3" %> 
  <%= link_to "Back to expenses", expenses_path ,class:"btn btn-warning mb-3" %>

  <%= button_to "Destroy this expense", @expense, method: :delete ,class:"btn btn-danger" %>
</div>

<p>
  <strong>Receipt:</strong>
  <% if @expense.receipt.attached? %>
    <%= image_tag @expense.receipt, size: "200x200" %>
  <% else %>
    No receipt uploaded.
  <% end %>
</p>
</center>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Expense</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", expenses_path, class: "nav-link active" %> 
        </li>
        
        <% if user_signed_in?%>

        <li class="nav-item">
          <%= link_to "Edit Profile",
          edit_user_registration_path,  class: "nav-link"
          %>
        </li>
         
        <li class="nav-item">
          <%= link_to "Expense Reports",
          reports_index_expenses_url,class: "nav-link"
          %>
        </li>
            
        <li class="nav-item">
          <%= link_to "Admin",
          new_admin_user_session_url ,class: "nav-link"
          %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up",
          new_user_registration_path,class: "nav-link"
          %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In",
          new_user_session_path,class: "nav-link"
          %>
        </li>
        
        <% end %>
      </ul>
       
      <%if user_signed_in?%>
      <ul class="navbar-nav ms-2">

      <li class="nav-item ml-5">
         <%= form_tag(expenses_path,class:"d-flex",method: :get) do %>
         <%= text_field_tag :search,params[:search],{class:"form-control me-2"}%>
         <%= submit_tag "Search",class:"btn btn-primary me-3"%>
         <% end %>    
      </li>
      <li class="nav-item">
          <%= button_to "Sign Out",
          destroy_user_session_path,
          method: :delete, data:{
            confirm: "Are You Sure?",
            turbo_confirm: "Are You Sure?"},
            class: "btn btn-outline-info"
          %>
      </li> 
      </ul>
      <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expence</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%if notice%>
    <p class="alert-success"><%=notice%></p>
    <%elsif alert%>
    <p class="alert-warning"><%=alert%></p>
    <%end%>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/index.html.erb
<div class="container">
<h1>Expense Reports</h1>

<h2>Expenses by Day</h2>
<%= column_chart current_user.expenses.group_by_day_of_week(:created_at, format: "%a").count %>

<h2>Expenses by Month</h2>
<%= line_chart current_user.expenses.group_by_month(:date, last: 6, current: true).sum('expenses.amount') %>
</div>